#:schema node_modules/wrangler/config-schema.json
name = "sub"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "2549db98f91f4f9f83b20d121de23e0c" }
]

[assets]
directory = "./public"
